baseURL = 'https://lfaus.github.io/circuit_breaker/'
languageCode = 'en-us'
title = 'Circuit Breaker Documentation'
theme = 'hugo-book'

# Book theme specific configurations
[params]
  # (Optional) Set Google Analytics if you use it to track your website.
  # googleAnalytics = "G-XXX"

  # (Optional) If you provide a Disqus shortname, comments will be enabled on
  # all pages.
  # disqusShortname = "my-site"

  # (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
  # You can remove all taxonomies by following config:
  disablePathToLower = true
  enableGitInfo = true

  # (Optional) Set this to true to enable 'Last Modified by' date and git author
  #  information on 'doc' type pages.
  BookRepo = 'https://github.com/lfaus/circuit_breaker'
  BookEditPath = 'edit/main/content'
