baseURL = 'https://castingclouds.github.io/cb-docs'
languageCode = 'en-us'
title = 'Circuit Breaker'
theme = 'hextra'

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = "Documentation"
    pageRef = "/docs"
    weight = 1

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/castingclouds/circuit_breaker"
    weight = 2

[params]
  description = "A powerful Ruby library for building AI-powered workflows and assistants"
  
  [params.footer]
    enable = true
    copyright = " 2025 Circuit Breaker"

  [params.search]
    enable = true
